# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d275dd7b9a491f0027fb19899fca47d93dc1e6876c79b3a4834b1a12527e0af57094a4ac80d231aad917f0037978033a964002ce52caa85227d826eb5a6e0db

test:
  secret_key_base: 617d4bffdab23bd90d0ea4ac5cdad7070f06d42d5f584f512589abe159bfe34dc431013bf4e45eee01495195be8c1e5e60d8526922cb7ad9298358accd8a8442

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
